### PR TITLE
Update repository/version variables to the latest phantomenv release.

### PR DESCRIPTION
**Pull request by lucasmazza**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I think that just this will not make it automatically work because the origin of the repository will not change. We need to thing a way to change the origin of existing clones

**Comment by lucasmazza** [comment]
@rafaelfranca makes sense to have this origin change checking inside the `repository` type?

**Comment by rafaelfranca** [comment]
@lucasmazza yes

**Comment by lucasmazza** [comment]
boxen/puppet-repository#14

**Pull request merged**
